VehicleRepairMVC/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VehicleRepairMVC.Context;
using VehicleRepairMVC.Models;

namespace VehicleRepairMVC.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly VehicleRepairDbContext _context;

        public AppointmentController(VehicleRepairDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.IsLoggedIn = HttpContext.Session.GetString("IsLoggedIn") == "true";
            return View();
        }

        [HttpPost]
        public ActionResult Index(Car car)
        {
            ViewBag.IsLoggedIn = HttpContext.Session.GetString("IsLoggedIn") == "true";
            int? loggedInUserId = HttpContext.Session.GetInt32("LoggedInUserId");

            car.UserID = loggedInUserId;


            if (ModelState.IsValid)
            {
                _context.Cars.Add(car);
                _context.SaveChanges();
                TempData["CarSuccessMessage"] = "Arabanız başarıyla eklendi. Randevu alabilirsiniz.";
                return RedirectToAction("AddAppointment");
            }

            return View(car);

        }

        public IActionResult AddAppointment() 
        {
            ViewBag.IsLoggedIn = HttpContext.Session.GetString("IsLoggedIn") == "true";
            int? loggedInUserId = HttpContext.Session.GetInt32("LoggedInUserId");

            var cars = _context.Cars
         .Where(c => c.UserID == loggedInUserId.Value)
         .Select(c => new SelectListItem
         {
             Value = c.CarID.ToString(),
             Text = c.LicensePlate
         })
         .ToList();

            ViewBag.Cars = cars;

            return View();
        }

        [HttpPost]
        public IActionResult AddAppointment(Appointment appointment)
        {
            ViewBag.IsLoggedIn = HttpContext.Session.GetString("IsLoggedIn") == "true";
            int? loggedInUserId = HttpContext.Session.GetInt32("LoggedInUserId");

            appointment.CreatedAt= DateTime.Now;
            appointment.Status = "Onay bekliyor";
            if (ModelState.IsValid)
            {
                _context.Appointments.Add(appointment);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Randevu isteğiniz başarıyla gönderildi. Admin işlem yaptıktan sonra randevularım veya bildirim kısmından randevu durumunu öğrenebilirsiniz.";
                return RedirectToAction("AddAppointment");
            }
            
            var cars = _context.Cars
           .Where(c => c.UserID == loggedInUserId.Value)
           .Select(c => new SelectListItem
           {
               Value = c.CarID.ToString(),
               Text = c.LicensePlate
           })
           .ToList();

            ViewBag.Cars = cars;

            return View(appointment);
        }
    }
}

VehicleRepairMVC/Controllers/NotificationController.cs
using Microsoft.AspNetCore.Mvc;
using VehicleRepairMVC.Context;
using VehicleRepairMVC.Models;

namespace VehicleRepairMVC.Controllers
{
    public class NotificationController : Controller
    {
        private readonly VehicleRepairDbContext _context;

        public NotificationController(VehicleRepairDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.IsLoggedIn = HttpContext.Session.GetString("IsLoggedIn") == "true";

            if (HttpContext.Session.GetInt32("LoggedInUserId").HasValue)
            {
                int loggedInUserId = HttpContext.Session.GetInt32("LoggedInUserId").Value;

                var userNotifications = _context.Notifications
                    .Where(n => n.UserID == loggedInUserId)
                    .Select(n => new NotificationViewModel
                    {
                        NotificationID = n.NotificationID,
                        NotificationText = n.NotificationText,
                        CreatedAt = n.CreatedAt,
                        AppointmentDate = n.Appointment.AppointmentDate,
                        LicensePlate = n.Appointment.Car.LicensePlate
                    })
                    .ToList();

                return View(userNotifications);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }
    }
}

VehicleRepairMVC/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VehicleRepairMVC.Context;

namespace VehicleRepairMVC.Controllers
{
    public class ProfileController : Controller
    {
        private readonly VehicleRepairDbContext _context;

        public ProfileController(VehicleRepairDbContext context)
        {
            _context = context;
        }

        public IActionResult MyAppointments()
        {
            ViewBag.IsLoggedIn = HttpContext.Session.GetString("IsLoggedIn") == "true";
            if (HttpContext.Session.GetInt32("LoggedInUserId").HasValue)
            {
                int? loggedInUserId = HttpContext.Session.GetInt32("LoggedInUserId");
                if (loggedInUserId.HasValue)
                {
                    var approvedAppointments = _context.Appointments
                        .Include(a => a.Car)
                        .Where(a => a.Car.UserID == loggedInUserId.Value && (a.Status == "Onaylandı" || a.Status=="İptal Edildi"))
                        .ToList();

                    return View(approvedAppointments);
                }
            }

            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public async Task<IActionResult> CancelAppointment(int appointmentId)
        {
            var appointment = await _context.Appointments.FindAsync(appointmentId);
            if (appointment == null)
            {
                return NotFound();
            }

            // Randevu tarihinden şu anki zamanı çıkararak fark oluştur
            var timeDifference = appointment.AppointmentDate - DateTime.Now;

            // Eğer randevu tarihi geçmişse veya fark 24 saatten az ise, randevuyu iptal etmeye izin verme
            if (timeDifference.TotalHours < 24)
            {
                TempData["ErrorMessage"] = "Randevuyu son 24 saat içinde iptal edemezsiniz!";
                return RedirectToAction("MyAppointments"); // Hata mesajıyla birlikte MyAppointments sayfasına yönlendir
            }

            // Randevuyu iptal etme işlemi
            appointment.Status = "İptal Edildi"; // Statusu güncelle
            await _context.SaveChangesAsync();

            return RedirectToAction("MyAppointments"); // Silme işlemi tamamlandıktan sonra MyAppointments sayfasına yönlendir.
        }

        public IActionResult MyVehicles()
        {
            ViewBag.IsLoggedIn = HttpContext.Session.GetString("IsLoggedIn") == "true";
            if (HttpContext.Session.GetInt32("LoggedInUserId").HasValue)
            {
                int? loggedInUserId = HttpContext.Session.GetInt32("LoggedInUserId");
                if (loggedInUserId.HasValue)
                {
                    var userCars = _context.Cars.Where(c => c.UserID== loggedInUserId.Value).ToList();
                    return View(userCars);
                }
            }
            return RedirectToAction("Index", "Login");
        }
    }
}

VehicleRepairMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Araba Tamiri Randevu Sitesi</title>


    <!-- bootstrap core css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" type="text/css" href="~/template/css/bootstrap.css" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

    <!-- font awesome style -->
    <link href="~/template/css/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/template/css/styles.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/template/css/responsive.css" rel="stylesheet" />

</head>

<body>
   
    <div class="hero_area">
        <partial name="_Navbar" />
        <!-- slider section -->
        <section class="slider_section ">
         <partial name="_MainPage" />

        </section>
        <!-- end slider section -->
    </div>
    @RenderBody()
    <section class="info_section mt-4 ">
    <div class="info_bottom">
            <div class="row justify-content-center">
            <div class="col-md-2">
                    <div class="info_logo">
                        <a href="">
                        <img src="~/template/images/logoo.png" alt="" style="width: 12rem; height: auto;">
                        </a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end info_section-->
<!-- footer   section -->    
<footer class="footer_section">
        <div class="container">    
        <p>
            &copy;     <span id="displayYear"></span> </a>
        </p>
    </div>
</footer>
<!-- footer section -->

    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/template/js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <!-- bootstrap js -->
    <script src="~/template/js/bootstrap.js"></script>
    <!-- owl slider -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <!--  OwlCarousel 2 - Filter -->
    <script src="https://huynhhuynh.github.io/owlcarousel2-filter/dist/owlcarousel2-filter.min.js"></script>
    <!-- custom js -->
    <script src="~/template/js/custom.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
    </script>
    <!-- End Google Map -->
</body>
</html>

VehicleRepairMVC/Views/Shared/_MainPage.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

<div id="customCarousel1" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="container ">
                <div class="row">
                    <div class="col-md-10 mx-auto">
                         @if (ViewBag.IsLoggedIn != null && ViewBag.IsLoggedIn)
                        {
                                 <div class="detail-box text-center">
                                <h1>
                                   SİTEYE HOŞGELDİN @Accessor?.HttpContext?.Session.GetString("Username")
                                </h1>
                                </div>
                        }
                        else{
                        <div class="detail-box">
                            <h1>
                                ARAÇ TAMİR <br>
                                RANDEVUSU İÇİN GİRİŞ YAPIN<br>
                                HESABINIZ YOKSA KAYIT OLUN
                            </h1>
                            <div class="btn-box">
                                <a href="/Login/Index" class="btn1">
                                    Giriş Yap
                                </a>
                                <a href="/Login/Register" class="btn2">
                                    Kayıt Ol
                                </a>

                            </div>
                        </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        @*<div class="carousel-item">
        <div class="container ">
        <div class="row">
        <div class="col-md-10 mx-auto">
        <div class="detail-box">
        <h1>
        ARCHITECT <br>
        BUILDER CONSTRUCTION <br>
        SERVICES
        </h1>
        <div class="btn-box">
        <a href="" class="btn1">
        Kullanıcı Girişi
        </a>
        <a href="" class="btn2">
        Admin Girişi
        </a>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        <ol class="carousel-indicators">
        <li data-target="#customCarousel1" data-slide-to="0" class="active"></li>

        </ol>*@
    </div>
</div>

VehicleRepairMVC/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

  <style>
        .quote_btn-container {
            display: flex;
            align-items: center;
        }
        .quote_btn {
            margin-right: 10px;
        }

        /* Custom Profile Menu */
    .profile-menu {
        position: relative;
        display: inline-block;
    }

    .profile-menu-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
        min-width: 160px;
        text-align: center; /* Ortalayan stil */
        left: 50%;
        transform: translateX(-50%);
    }

        .profile-menu-content a {
            background-color: #f07b26; /* Arka plan rengi */
            color: white; /* Yazı rengi */
            padding: 5px 10px; /* Daha küçük padding */
            text-decoration: none;
            display: block;
            font-size: 12px; /* Daha küçük yazı */
            text-align: center; /* Metni ortalama */
        }

            .profile-menu-content a:hover {
                background-color: #f1f1f1;
            }

    .profile-menu:hover .profile-menu-content {
        display: block;
    }
    </style>
 <!-- header section strats -->
<header class="header_section">

    <div class="header_bottom">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg custom_nav-container ">
                <a class="navbar-brand" href="/Home/Index">
                    <img src="~/template/images/logoo.png" alt="">
                </a>


                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class=""> </span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    @if (ViewBag.IsLoggedIn != null && ViewBag.IsLoggedIn)
                    {
                        <ul class="navbar-nav  ">
                            <li class="nav-item active">
                                <a class="nav-link" href="/Home/Index">ANASAYFA <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href=/Home/Index/#service_section>HİZMETLERİMİZ</a>
                            </li>
                            <li class="nav-item">
                                    <a class="nav-link" href=/Home/Index/#about>HAKKIMIZDA</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Products" asp-controller="Home">ÜRÜNLER</a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="Index" asp-controller="Appointment" class="nav-link">RANDEVU İŞLEMİ</a>
                            </li>
                        </ul>
                        <div class="quote_btn-container">
                            <a asp-action="Index" asp-controller="Notification" class="quote_btn btn btn-primary mr-2">
                                <i class="fa-solid fa-bell" style="color: #ffffff; margin-right:3px;"></i>
                                BİLDİRİMLER
                            </a>

                            <!-- Dropdown Menu for Profile -->
                            <div class="profile-menu">
                                <button class="quote_btn btn btn-primary mr-2">
                                    <i class="fa-solid fa-user" style="color: #ffffff; margin-right:3px;"></i>
                                    PROFİL
                                </button>
                                <div class="profile-menu-content">
                                    <a asp-action="MyAppointments" asp-controller="Profile">Randevularım</a>
                                    <a asp-action="MyVehicles" asp-controller="Profile">Araçlarım</a>
                                </div>
                            </div>

                            <a asp-action="Logout" asp-controller="Login" class="quote_btn">
                                <i class="fa-solid fa-right-from-bracket"></i>
                                ÇIKIŞ YAP
                            </a>
                        </div>
                    }
                    else
                    {
                             <ul class="navbar-nav  ">
                                <li class="nav-item active">
                                    <a class="nav-link" href="/Home/Index">ANASAYFA <span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href=#service_section>HİZMETLERİMİZ</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href=#about>HAKKIMIZDA</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href=#product>ÜRÜNLER</a>
                                </li>
                                <li class="nav-item">
                                <a class="nav-link" asp-action="AdminLogin" asp-controller="Login">ADMİN GİRİŞİ</a>
                                </li>
                            </ul>
                            <div class="quote_btn-container">
                                <a href="/Login/Index" class="quote_btn">
                                    GİRİŞ YAP
                                </a>
                            </div>
                    }
                </div>
            </nav>
        </div>
    </div>
</header>
<!-- end header section -->

VehicleRepairMVC/Views/Shared/_SecondLayout.cshtml
<!DOCTYPE html>
<html>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Araba Tamiri Randevu Sitesi</title>


    <!-- bootstrap core css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" type="text/css" href="~/template/css/bootstrap.css" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

    <!-- font awesome style -->
    <link href="~/template/css/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/template/css/styles.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/template/css/responsive.css" rel="stylesheet" />

</head>

<body>


        <partial name="_Navbar" />
        <!-- slider section -->
        <!-- end slider section -->
    @RenderBody()
    <!-- footer section -->
      <section class="info_section mt-4">
    <div class="info_bottom">
            <div class="row justify-content-center">
            <div class="col-md-2">
                    <div class="info_logo">
                        <a href="">
                        <img src="~/template/images/logoo.png" alt="" style="width: 12rem; height: auto;">
                        </a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end info_section-->
<!-- footer   section -->    
<footer class="footer_section">
        <div class="container">    
        <p>
            &copy;     <span id="displayYear"></span> </a>
        </p>
    </div>
</footer>
    <!-- footer section -->
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/template/js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <!-- bootstrap js -->
    <script src="~/template/js/bootstrap.js"></script>
    <!-- owl slider -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <!--  OwlCarousel 2 - Filter -->
    <script src="https://huynhhuynh.github.io/owlcarousel2-filter/dist/owlcarousel2-filter.min.js"></script>
    <!-- custom js -->
    <script src="~/template/js/custom.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
    </script>
    <!-- End Google Map -->
</body>
</html>