VehicleRepairMVC/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Dynamic;
using VehicleRepairMVC.Context;

namespace VehicleRepairMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        private readonly VehicleRepairDbContext _context;
        public DashboardController(VehicleRepairDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var carUsers = from car in _context.Cars
                           join user in _context.Users on car.UserID equals user.UserID
                           select new
                           {
                               car.Brand,
                               car.Model,
                               car.Year,
                               car.LicensePlate,
                               user.Firstname,
                               user.Lastname,
                               user.Username
                           };

            var expandoList = new List<ExpandoObject>();
            foreach (var item in carUsers)
            {
                dynamic expando = new ExpandoObject();
                expando.Brand = item.Brand;
                expando.Model = item.Model;
                expando.Year = item.Year;
                expando.LicensePlate = item.LicensePlate;
                expando.Firstname = item.Firstname;
                expando.Lastname = item.Lastname;
                expando.Username = item.Username;
                expandoList.Add(expando);
            }

            return View(expandoList);
        }

    }
}

VehicleRepairMVC/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VehicleRepairMVC.Context;
using VehicleRepairMVC.Models;

namespace VehicleRepairMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly VehicleRepairDbContext _context;

        public ProductController(VehicleRepairDbContext context)
        {
            _context = context;
        }

        //public IActionResult Index()
        //{
        //    var products = _context.Products.ToList();
        //    return View(products);
        //}

        public async Task<IActionResult> Index()
        {
            var products = await _context.Products.ToListAsync();
            return View(products);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateStock(int productId, int newStock)
        {
            var product = await _context.Products.FindAsync(productId);
            if (product == null)
            {
                return NotFound();
            }

            product.Stock = newStock;
            _context.Update(product);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                 _context.Products.Add(product);
                 _context.SaveChanges();
                TempData["SuccessMessage"] = "Ürün başarıyla eklendi.";
                return RedirectToAction("Create");
            }
            TempData["Error Message"] = "Ürün eklenemedi!";
            return View(product);
        }
    }
}

VehicleRepairMVC/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VehicleRepairMVC.Context;
using VehicleRepairMVC.Models;

namespace VehicleRepairMVC.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly VehicleRepairDbContext _context;

        public AppointmentController(VehicleRepairDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.IsLoggedIn = HttpContext.Session.GetString("IsLoggedIn") == "true";
            return View();
        }

        [HttpPost]
        public ActionResult Index(Car car)
        {
            ViewBag.IsLoggedIn = HttpContext.Session.GetString("IsLoggedIn") == "true";
            int? loggedInUserId = HttpContext.Session.GetInt32("LoggedInUserId");

            car.UserID = loggedInUserId;


            if (ModelState.IsValid)
            {
                _context.Cars.Add(car);
                _context.SaveChanges();
                TempData["CarSuccessMessage"] = "Arabanız başarıyla eklendi. Randevu alabilirsiniz.";
                return RedirectToAction("AddAppointment");
            }

            return View(car);

        }

        public IActionResult AddAppointment() 
        {
            ViewBag.IsLoggedIn = HttpContext.Session.GetString("IsLoggedIn") == "true";
            int? loggedInUserId = HttpContext.Session.GetInt32("LoggedInUserId");

            var cars = _context.Cars
         .Where(c => c.UserID == loggedInUserId.Value)
         .Select(c => new SelectListItem
         {
             Value = c.CarID.ToString(),
             Text = c.LicensePlate
         })
         .ToList();

            ViewBag.Cars = cars;

            return View();
        }

        [HttpPost]
        public IActionResult AddAppointment(Appointment appointment)
        {
            ViewBag.IsLoggedIn = HttpContext.Session.GetString("IsLoggedIn") == "true";
            int? loggedInUserId = HttpContext.Session.GetInt32("LoggedInUserId");

            appointment.CreatedAt= DateTime.Now;
            appointment.Status = "Onay bekliyor";
            if (ModelState.IsValid)
            {
                _context.Appointments.Add(appointment);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Randevu isteğiniz başarıyla gönderildi. Admin işlem yaptıktan sonra randevularım veya bildirim kısmından randevu durumunu öğrenebilirsiniz.";
                return RedirectToAction("AddAppointment");
            }
            
            var cars = _context.Cars
           .Where(c => c.UserID == loggedInUserId.Value)
           .Select(c => new SelectListItem
           {
               Value = c.CarID.ToString(),
               Text = c.LicensePlate
           })
           .ToList();

            ViewBag.Cars = cars;

            return View(appointment);
        }
    }
}

VehicleRepairMVC/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Araba Tamiri Admin Sayfası</title>


    <!-- bootstrap core css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" type="text/css" href="~/template/css/bootstrap.css" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

    <!-- font awesome style -->
    <link href="~/template/css/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/template/css/styles.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/template/css/responsive.css" rel="stylesheet" />

</head>

<body>
   
        <partial name="_Navbar" />

    @RenderBody()
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/template/js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <!-- bootstrap js -->
    <script src="~/template/js/bootstrap.js"></script>
    <!-- owl slider -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <!--  OwlCarousel 2 - Filter -->
    <script src="https://huynhhuynh.github.io/owlcarousel2-filter/dist/owlcarousel2-filter.min.js"></script>
    <!-- custom js -->
    <script src="~/template/js/custom.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
    </script>
    <!-- End Google Map -->
</body>
</html>

VehicleRepairMVC/Areas/Admin/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

 <!-- header section strats -->
<header class="header_section">

    <div class="header_bottom">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg custom_nav-container ">
                <a class="navbar-brand" href="/Home/Index">
                    <img src="~/template/images/logoo.png" alt="">
                </a>


                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class=""> </span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav  ">
                            <li class="nav-item active">
                                <a class="nav-link" asp-action="Index" asp-controller="Dashboard">DASHBOARD<span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="Appointment">RANDEVU YÖNETİMİ</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="Product">ÜRÜN YÖNETİMİ</a>
                            </li>
                        </ul>
                        <div class="quote_btn-container">
                            <a asp-area="" asp-action="Index" asp-controller="Home" class="quote_btn">
                                <i class="fa-solid fa-right-from-bracket"></i>
                                ÇIKIŞ YAP
                            </a>
                        </div>
                </div>
            </nav>
        </div>
    </div>
</header>
<!-- end header section -->